name: UpCommands
main: NoobMCBG\UGWE\Main
api: 4.0.0
version: 1.0.0
author: NoobMCBG

commands:
  /up:
    description: UpCommands
    permission: up.command
permissions:
  up.command:
    default: op
